### ISSUE TITLE
py3 branch not working on linux

### ISSUE THREAD

**Issue by mbuchheim** [snmishra/ftd2xx#10]
Hi,
I am very new to github, so I am not sure this is the correct way to report issues.
I am running Python 3.5 on a 64bit Arch Linux system. I installed ftd2xx via pip.

The correct sys.platform response for python 3 on Linux is 'linux' and not 'linux2' as written in file ftd2xx.py, line 12.

sys.platform.startswith('linux') could be a fix for py2 and py3.

**Comment by snmishra** [comment]
I am sorry, Krishna (ctrl-shift-esc) has offered to take over maintenance. His repo is at https://github.com/ctrl-shift-esc/ftd2xx. If it's not too much trouble, would you mind opening this issue on his repo?

**Comment by snmishra** [comment]
Closed for no further communication

**Comment by qxlsz** [comment]
I cannot open an issue in Krishna s repo :/
