### ISSUE TITLE
Which to fork: ctrl-shift-esc, or mtikekar?

### ISSUE THREAD

**Issue by capn-freako** [snmishra/ftd2xx#11]
Hi,

I'd like to prepare for contributing to this effort, by creating my own fork.
It looks like @ctrl-shift-esc has been officially designated as the project maintainer.
However, @mtikekar has made more recent changes to the code.
From whom should I create my own fork?

Thanks,
-db

**Comment by mtikekar** [comment]
I am not the official maintainer and I never really intended for my changes to get pulled into the main repository. So some of the changes probably break backwards compatibility. That said, if any of my changes interest you, I'd be happy to clean up my code and make a pull request.

**Comment by capn-freako** [comment]
Okay, thanks! I'll fork from @ctrl-shift-esc and stay in touch w/ you, re: you're development efforts.

Just FYI, my intent is to contribute convenient JTAG functionality to this package, if it doesn't already exist. (I haven't checked, yet.)

Cheers,
-db

**Comment by snmishra** [comment]
Sorry, didn't see this until now. Looks like @capn-freako got his answer.

**Comment by ctrl-shift-esc** [comment]
Actually another guy has contacted me and I'm also curious about this
question. Do you know how the _ftd2xx.py script was generated? The guy had
tried to use a FT4222 chip and it doesn't seem to work. So he wants to
integrate API from the new DLL.

**Comment by capn-freako** [comment]
No, sorry. I'm completely unfamiliar with the xml2py tool.
-db

**Comment by snmishra** [comment]
I had used h2xml and xml2py from ctypeslib to generate the _ft2dxx.py script. I am not sure what happened to the h2xml script, but I can't find it anymore.

**Comment by qxlsz** [comment]
@ctrl-shift-esc  I can't open issue in your repo

here is my issue. Unable to open a connection even though it lists the device serial number
```
In [33]: import ftd2xx as ft

In [34]: ft.listDevices()
Out[34]: [b'AL05J8AO']

In [35]: ft.openEx('AL05J8AO', ft.ftd2xx.OPEN_BY_SERIAL_NUMBER)
---------------------------------------------------------------------------
DeviceError                               Traceback (most recent call last)
<ipython-input-35-13985c480db4> in <module>
----> 1 ft.openEx('AL05J8AO', ft.ftd2xx.OPEN_BY_SERIAL_NUMBER)

~/.dirty/3/ftd2xx/ftd2xx/ftd2xx.py in openEx(id_str, flags)
    106     instance for it"""
    107     h = _ft.FT_HANDLE()
--> 108     call_ft(_ft.FT_OpenEx, id_str, _ft.DWORD(flags), c.byref(h))
    109     return FTD2XX(h)
    110

~/.dirty/3/ftd2xx/ftd2xx/ftd2xx.py in call_ft(function, *args)
     42     status = function(*args)
     43     if status != _ft.FT_OK:
---> 44         raise DeviceError(status)
     45
     46 def listDevices(flags=0):

DeviceError: DEVICE_NOT_FOUND

In [36]: ft.createDeviceInfoList()
Out[36]: 1
```

**Comment by qxlsz** [comment]
any idea @snmishra  @mtikekar  @ctrl-shift-esc ?
