### ISSUE TITLE
eeProgram

### ISSUE THREAD

**Issue by pazucj** [snmishra/ftd2xx#13]
Hello, when I use that function on Ubuntu I got error Access memory violation (Raspberry Pi 3 and Ubuntu 16.04)
I created handler, opened device and call eeProgram function like this
`h = _ft.FT_HANDLE()`
`call_ft(_ft.FT_Open, 0, c.byref(h))`
`dev = FTD2XX(h)`
`dev.eeProgram()`

**Comment by snmishra** [comment]
I no longer maintain this program. You might have better luck with one of the forks. https://github.com/ctrl-shift-esc/ftd2xx

**Comment by pazucj** [comment]
I can't write to them because only u have issues on Yours fork

**Comment by snmishra** [comment]
That's unfortunate. Sorry can't really help, as my time is limited and I
don't have a ftdi device any more. If you submit a patch, I'll take it
though.

Thanks
Satya

-- 
Satya Mishra
https://github.com/snmishra
