### ISSUE TITLE
How to write non-string data?

### ISSUE THREAD

**Issue by williamhuang03** [snmishra/ftd2xx#15]
It seems like I am required to send data as a string if I would like to write to the FTDI device, however the data I would like to send encompasses the entire uint8 range (0x00-0xFF). How should I go about sending these data if I cannot represent them as a string?

For example:
I would like to write the following:
`data = [0xAA, 0x02, 0x00, 0x01]`
What I tried:
```
dataString = ''.join([chr(e) for e in data])
device.write(dataString)
```

I would get an error: 
`ctypes.ArgumentError: argument 2: <class 'ValueError'>: embedded null character`

Thanks

**Comment by harvie256** [comment]
You can pass in a bytes object directly.  In fact this is the only way it works properly with python3 16b Unicode strings.

So your code would become:
`data = bytes([0xAA, 0x02, 0x00, 0x01])
device.write(bytes)
`

**Comment by snmishra** [comment]
@williamhuang03 as @harvie256 suggested, `bytes` is the way to do any IO in Python 3 and it works in Python 2. str is for Unicode strings.
