### ISSUE TITLE
Equivalent of FT_GetComPortNumber 

### ISSUE THREAD

**Issue by CaptainJL** [snmishra/ftd2xx#19]
Hey all,

I was wondering if there was the equivalent function of the raw C/C++ FT_GetComPortNumber?
I want to be able to scan COM port names (COM6 for example) (before or after opening ports is fine), however I am not sure of how to do it in this python wrap of the FTD2XX driver. 

Ideally I would like to open the device with COM port name, but just being able to determine the COM port name would significantly help.

Is there any way currently implemented to read the COM port number associated with a device number?

Thanks,
CaptainJL

**Comment by snmishra** [comment]
This fork by @cbrx-fw has this functionality: https://github.com/cbrx-fw/ftd2xx. If they agree, I can merge. Or if you want to implement it and create a PR, that'd be great too.

**Comment by ubichsel** [comment]
Hey snmishra

Would be nice if you could merge this function and release it to pypy. Thanks for all your good work!

**Comment by snmishra** [comment]
@ubichsel @CaptainJL  1.1.2 include getComPortNumber and is active on pypi.
