### ISSUE TITLE
Your license file is a little off

### ISSUE THREAD

**Issue by hmaarrfk** [snmishra/ftd2xx#21]
https://github.com/snmishra/ftd2xx/blob/3033019cc601f372b5b3d5d332d809895fba7705/LICENSE#L3

And you should probably add it to the sdist by creating a setup.cfg like:
https://github.com/scikit-image/scikit-image/blob/master/setup.cfg#L2

**Comment by snmishra** [comment]
Thanks for noticing. Fixed in `master`
