### ISSUE TITLE
Undefined symbol 'stime'

### ISSUE THREAD

**Issue by nathanrpage97** [snmishra/ftd2xx#33]
It looks like in the linux version there is an undefined reference to 'stime'

```log
_ftd2xx_linux.py in <module>
   1506 /usr/include/time.h:283"""
   1507 # /usr/include/time.h 294
-> 1508 stime = _libraries['libftd2xx.so'].stime
   1509 stime.restype = c_int
   1510 # stime(__when)
```

Commenting out the stime ctypes wrapper fixes this issue.

**Comment by nathanrpage97** [comment]
[Reference explaining its removal](https://lwn.net/Articles/811315/)

**Comment by snmishra** [comment]
@nathanrpage97  it’s fixed in the beta version. Please try 1.2.0-b.2 or 3 (coming soon)

**Comment by krister-ts** [comment]
Now that PR is linked and package versions with the fix are in this thread, maybe the issue should be closed.
