### ISSUE TITLE
Installation trouble on macOS Big Sur (11.1)

### ISSUE THREAD

**Issue by cedmfr** [snmishra/ftd2xx#34]
After installation by either ipython -m pip install ftd2xx or sudo -H pip install ftd2xx I've a OSError "OSError: dlopen(/usr/local/lib/libftd2xx.dylib, 6): image not found" How to fix this ? When I try to import I've the error :
OSError: dlopen(/usr/local/lib/libftd2xx.dylib, 6): image not found
Best regards,

**Comment by krister-ts** [comment]
Which driver have you installed from ftdi?

**Comment by snmishra** [comment]
@cedmfr This package does require that you install the driver separately. If you have the drivers installed, it might be because of new security features in macOS. I don't know how to work around those.

**Comment by cedmfr** [comment]
Yes! Thanks, I needed to install the driver from https://ftdichip.com/drivers/d2xx-drivers/ and follow successfully the ReadMe.rtf file.

**Comment by snmishra** [comment]
Glad it worked.
