### ISSUE TITLE
BadCommand when sending 2 commands

### ISSUE THREAD

**Issue by forestomir** [snmishra/ftd2xx#36]
**Describe the bug**
sending single command (e.g "\x80\x00\x03") works fine (right output is set to right logic state) though sending multiple commands (e.g. "\x80\x00\x03\x80\x03\x03") results in "BadCommand" ("\xfa") response

**To Reproduce**
Steps to reproduce the behaviour:
1. open connection to FT4232H in MPSSE mode
2. write a sequence of 2 commands "Set Data bits LowByte (\x80)"
3. read content of input buffer
whole initialization can be found at: [ftdi_test.py.txt](https://github.com/snmishra/ftd2xx/files/6821306/ftdi_test.py.txt)
with results as below. Sending 2 commands in a sequence looks like is actually executing the first command (correct inputs are being set to proper logic state) and the other command triggers "Bad command": 
![ftdi_test_results](https://user-images.githubusercontent.com/87059648/125751157-9f7a4c24-a551-4164-8646-f99e381eb0ec.png)

**Expected behaviour**
commands are send and executed sequentially, afterwards read of input buffer returns no elements

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - python 3.9.6
 - ftd2xx.dll from "CDM v2.12.36.2 WHQL Certified"
 - ftd2xx python library 1.1.2

**Additional context**
I know that my hardware setup is capable of receiving long command sequences because i was able to successfully perform I2c operations using same HW but on ubuntu with pyFtdi library. However I must run it on Win10_64 with ftd2xx.dll. At first glance it looks like dll problem and I will be also contacting FTDI about it though maybe one of you had similar problem. Please advise

**Comment by krister-ts** [comment]
In the mean time, I would suggest using a try/except where the bad command is handled by purge of the buffers and retrying the write.

I can't say that I have found an issue with the ftdi driver... However, that could explain some quirks that I had wrote off as bugs in the device firmware (and handled in the way mentioned above).

**Comment by snmishra** [comment]
@forestomir  I have no insight into why it's not working with FTDI driver and works with PyFtdi. Couple of things to try:
1. May be try a different baud rate? If the hardware is marginal, may be some timings are off?
2. You c[an use PyFtdi on Windows](https://eblot.github.io/pyftdi/installation.html#windows) apparently.

**Comment by forestomir** [comment]
hello, I think I got to the bottom of the issue :) but from begining.

regarding PyFtdi. I [tried ](https://github.com/eblot/pyftdi/issues/259#)to set it up on windows but the bottom line is that this project does not formally support Windows. Suggested workarounds are possible but are too complicated in my case since i need to run the final app on other users PCs with the least "developer tweaks". So I need to use ftd2xx.dll from official FTDI...

I played a little more with sending commands to ftdi. I focused on I2C applications using BDBUS0(TCK) as I2C clock, and BDBUS1(TDI) as I2C data output, BDBUS2(TDO) as I2C data input. As an experiment I tried to clock out any data so I send 0xAA with command: 
ftdiHandle.write('\x11\x00\x00\xAA')
as result I got no BadCommand and on osciloscope I got 8 clock cycles but no data appeared (data line constantly Low). Then I send more data with 
ftdiHandle.write('\x11\x01\x00\xAA\xAA')
as a result I got no BadCommand and on oscilloscope I got 10*8 clock cycles and some random data on SDA line (0x00 0x01 0x00 0x07 0xF8 0x00 0x3F 0x40 0x00)!!! So the data do appear bit with strange amount and value

so I tried different approach to sending commands:
ftdiHandle.write(chr(0x11))
ftdiHandle.write(chr(0x01))
ftdiHandle.write(chr(0x00))
ftdiHandle.write(chr(0xAA))
ftdiHandle.write(chr(0xAA))
and it works! On oscilloscope I see 2*8 clock cycles and data line contains two 0xAA

It looks like the problem is with sending string of '\x11\x00\x00\xAA' to ftd2xx.dll. This data (apparently) are not being seen by dll as array of 4 bytes but rather as a memory space that might have been padded by Windows with random data. This might be related with function "write" at ftd2xx.py that converts the string to be passed to dll by reference

def write(self, data):
...."""Send the data to the device. Data must be a string representing the
....bytes to be sent"""
....w = _ft.DWORD()
....call_ft(_ft.FT_Write, self.handle, data, len(data), **c.byref**(w))
....return w.value 

This is just suggestion, I am not an expert on that. Anyway, for me I will just send bytes one by one and that will work for me. Hope this helps to contribute to the project

**Comment by snmishra** [comment]
@forestomir Thanks for digging into this. I think `write` expects a [bytes object](https://docs.python.org/3/c-api/bytes.html) and not a string. I think I might add some type annotations there to make it clear. Please try ` ftdiHandle.write(b'\x11\x01\x00\xAA\xAA')`

**Comment by krister-ts** [comment]
> @forestomir Thanks for digging into this. I think `write` expects a [bytes object](https://docs.python.org/3/c-api/bytes.html) and not a string. I think I might add some type annotations there to make it clear. Please try ` ftdiHandle.write(b'\x11\x01\x00\xAA\xAA')`

Beat me to it. Yes, python 3 strings won't work correctly.
