### ISSUE TITLE
unplugged device

### ISSUE THREAD

**Issue by forestomir** [snmishra/ftd2xx#38]
Noob allert!

Is there a way to asynchronously detect FTDI was unplugged?  
Maybe "setEventNotification" can be helpful. Any good examples of usage?

**Comment by snmishra** [comment]
I don't know that it's possible from FTDI library. The OS may generate an event. If you're using Windows, you could try pywin32. Here's a blog I found via web search: http://timgolden.me.uk/python/win32_how_do_i/detect-device-insertion.html

**Comment by forestomir** [comment]
thank you @snmishra for hint
