### ISSUE TITLE
Cycling port... DEVICE_NOT_OPENED

### ISSUE THREAD

**Issue by RyanHope** [snmishra/ftd2xx#39]
Run this code and while it is running, repeatedly disconnect/reconnect an ftdi adapter. At some point something breaks and the serial returned by getDeviceInfoDetail is an empty string and opening the device fails. Sometimes the device will come back after another cycle but other times it seems like its stuck "forever". Eventually it will work again but not sure what gets it working again.

```
import ftd2xx
import time

if __name__ == "__main__":
    while True:
        print("--------------------------")
        for i in range(ftd2xx.createDeviceInfoList()):
            try:
                serial = ftd2xx.getDeviceInfoDetail(i, False)["serial"]
                print(i, serial)
                dev = ftd2xx.open(i)
                dev.close()
            except ftd2xx.ftd2xx.DeviceError as e:
                print(e)
        time.sleep(.1)
```

**Comment by krister-ts** [comment]
Pass ``update=False`` to ``getDeviceDetails()`` so you don't create the device info list again.

Hopefully that is your issue here.

**Comment by krister-ts** [comment]
@snmishra Should ``open()`` have an update kwarg?

**Comment by snmishra** [comment]
@RyanHope What is the purpose of this test. Doesn't feel like a typical use case. It's possible some state is not getting reset somewhere in the stack if `dev.close()` is not called (because device doesn't exist)

@krister-ts What would the `update` kwarg do?

**Comment by RyanHope** [comment]
I have an ECU flashing utility that uses FTDI devices. In the app is a drop
down list of all the FTDI adapters present on the system. Since there is no
hotplug support, I need to constantly poll for new devices. One of the
things I test, is that I can unplug-replug devices without my app crashing
or without hitting any bugs. So I am hitting this issue in production code,
the example I pasted was just a minimal working example of how to trigger
the issue.

**Comment by snmishra** [comment]
@RyanHope I think someone else also wanted to detect when a device is unplugged. I think it may make sense to use the `aio` interface that @krister-ts made. That one should allow you to use a timeout to cleanup if the device is unplugged.

Alternatively, you could use the OS provided facility as discussed in #38 to detect when device has been unplugged and restart your main program.

Handling device removal is probably beyond the scope of this library. The library is meant to provide a Python-friendly way to use the DLL provided by FTDI.

**Comment by krister-ts** [comment]
> @krister-ts What would the `update` kwarg do?

@snmishra The class init has an update kwarg. Why not allow the device info list update to be prevented when it has already been created in the user's script?

All the user wants to open is the index from the first list, not an updated list.

In the case where the user blindly tries to open first device, the update is necessary. This should remain the default.

**Comment by snmishra** [comment]
@krister-ts I checked the code for `open` and `openEx` and there is no call to `createDeviceInfoList`. Am I missing something?

**Comment by krister-ts** [comment]
> @krister-ts I checked the code for `open` and `openEx` and there is no call to `createDeviceInfoList`. Am I missing something?

Yes, it is hidden. The ``FTD2XX`` class that is returned has the kwarg ``update`` (default True).

**Comment by snmishra** [comment]
@krister-ts Ah, I see. Definitely makes sense. I’m traveling right now, do you want to make a PR? Otherwise, I should be able to get to it in a day or two.

**Comment by krister-ts** [comment]
@snmishra I can do it.

**Comment by snmishra** [comment]
@RyanHope There was a hidden call to `createDeviceInfoList`. @krister-ts  added an `update` option to open. You should set it to `False`, in your code and see if that helps. The fix is released in v1.3.0-beta.1. If that works for you, I'll make a release.

**Comment by RyanHope** [comment]
I pulled the change last night and rebuilt my project... didn't notice an improvement. It's super hit and miss. If I hot plug a device, sometimes it reappears right away and other times I have to re-hotplug it a dozen or more times before it will show up again.

**Comment by krister-ts** [comment]
> I pulled the change last night and rebuilt my project... didn't notice an improvement. It's super hit and miss. If I hot plug a device, sometimes it reappears right away and other times I have to re-hotplug it a dozen or more times before it will show up again.  

If you have added ``False`` to your call to ``open()`` and there is no competing background service, I'm suspecting there may be an issue at low level.

All I can suggest is to verify that your hardware is in fact enumerating.

**Comment by RyanHope** [comment]
Ok well, to be fair, I am plugging a device into a hub, so that might be complicating things a little. As mentioned earlier my example is a little extreme and I don't expect users to constantly hotplug devices. I just happened to notice the issue while testing for edge cases/bugs in my app. I will dig a little more into it.

**Comment by krister-ts** [comment]
@RyanHope Not related to your issue, just curious... What is your application?

**Comment by RyanHope** [comment]
I have a bunch of software projects all related to flashing different motorcycle ECUs.

**Comment by krister-ts** [comment]
Nice! I hope it works out

**Comment by snmishra** [comment]
Closing for now as we need more info to debug. Feel free to re-open if we find something that we could work on.
