### ISSUE TITLE
Missing dependency async-timeout

### ISSUE THREAD

**Issue by lovetheguitar** [snmishra/ftd2xx#41]
Hello all,

[here](https://github.com/snmishra/ftd2xx/blob/625d727a932c5e42f9cd2923df6faadafb6f714f/ftd2xx/aio/aio.py#L5) you import async-timeout.

This dependency should be added to the setup in some way. 

Thanks for your work. :)

**Comment by snmishra** [comment]
Done

**Comment by lovetheguitar** [comment]
Hi @snmishra,

sorry again for not replying. Somehow I only saw the closing notification now.

Imho this was not ‘done’. I was not using any async stuff still I got an import error and had to install the dependency.

So if it is an optional dependency, it should only fail when trying to use that specific functionality.

**Comment by lovetheguitar** [comment]
The output a user gets after installing the latest release:

```bash
import` ftd2xx
/usr/local/lib/python3.8/dist-packages/ftd2xx/__init__.py:13: in <module>
    from . import aio
/usr/local/lib/python3.8/dist-packages/ftd2xx/aio/__init__.py:6: in <module>
    from .aio import FTD2XX, open, openEx
/usr/local/lib/python3.8/dist-packages/ftd2xx/aio/aio.py:5: in <module>
    import async_timeout
E   ModuleNotFoundError: No module named 'async_timeout'
```
