### ISSUE TITLE
.pthread_yield

### ISSUE THREAD

**Issue by gek47** [snmishra/ftd2xx#43]
Seeing the following error:
AttributeError: /usr/lib/libftd2xx.so: undefined symbol: pthread_yield. Did you mean: 'pthread_kill'?

which is coming from line 741 in _ftd2xx_linux.py 

google says ptheard_yield is deprecated

https://man7.org/linux/man-pages/man3/pthread_yield.3.html

I'm on archlinux: 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux

I think this may have broken when  I updated arch today.  All was ok a coupe of days ago.  FYI: libftd2xx is libftd2xx.so.1.4.24

Thanks
gek

**Comment by krister-ts** [comment]
I have put in a pull request that should resolve this issue.
@gek47 Sorry it has taken so long to respond to your issue. Are you still stuck on this?
