### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by gek47** [snmishra/ftd2xx#47]
with the latest version on import of ftd2xx

ftd2xx/_ftd2xx_linux.py", line 92, in pthread_cond_t
    ("__align", __pthread_cond_align_t),
NameError: name '_pthread_cond_t__pthread_cond_align_t' is not defined

**Comment by snmishra** [comment]
@gek47 A recent PR from @krister-ts should have fixed this. Could you check if master branch solves the issue. If so I’ll make a release.

**Comment by gek47** [comment]
the version I tested: 1.3.0-beta.2

Also tried on a clean VM install of Archlinux and got the same error.

Thanks
g

**Comment by snmishra** [comment]
@gek47 1.3.0-beta.2 is not the latest from master branch. Please try directly from master using `pip install git+https://github.com/snmishra/ftd2x`

**Comment by gek47** [comment]
Same error, 

master branch on github the file myversion.txt is 1.3.0-beta.2, the egg info in site-packages is `ftd2xx-1.3.0b2-py3.10.egg-info`

thanks for your help,
g

**Comment by gek47** [comment]
sorry closed by accident

**Comment by snmishra** [comment]
> Same error,
> 
> master branch on github the file myversion.txt is 1.3.0-beta.2, the egg info in site-packages is `ftd2xx-1.3.0b2-py3.10.egg-info`
> 
> thanks for your help, g

Ah, that's a good point. May be you need `-U` flag to ensure the master branch overwrites what you got from PyPI. `pip install -U git+https://github.com/snmishra/ftd2xx`

**Comment by gek47** [comment]
Same import error

g

**Comment by snmishra** [comment]
Could you give the details for your platform, such as distro, distro version, python version? Also complete logs would be great.

**Comment by gek47** [comment]
Platform: Linux/AMD5800X

Distro is Arch linux 
arch is a rolling distro and has been updated today


`
python 3.10.4

lrwxrwxrwx 1 root root     28 Dec 21 13:34 libftd2xx.so -> /usr/lib/libftd2xx.so.1.4.24
-rwxr-xr-x 1 root root 316128 Dec 21 13:34 libftd2xx.so.1.4.24



# uname -a

[gek@kaos venv]$ uname -a
Linux kaos.podzil.com 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux


# create new virtual environment

[gek@kaos venv]$ python -m venv ftdi


# activate environment

[gek@kaos venv]$ source ftdi/bin/activate


# install ftd2xx

(ftdi) [gek@kaos venv]$ pip install -U git+https://github.com/snmishra/ftd2xx
Collecting git+https://github.com/snmishra/ftd2xx
  Cloning https://github.com/snmishra/ftd2xx to /tmp/pip-req-build-9hrjlbxw
  Running command git clone --filter=blob:none --quiet https://github.com/snmishra/ftd2xx /tmp/pip-req-build-9hrjlbxw
  Resolved https://github.com/snmishra/ftd2xx to commit 360b3ae761023f822ce0dd7d26238092b07e2663
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for ftd2xx, since package 'wheel' is not installed.
Installing collected packages: ftd2xx
  Running setup.py install for ftd2xx ... done
Successfully installed ftd2xx-1.3.0b2
(ftdi) [gek@kaos venv]$ 


# start python and import ftd2xx

(ftdi) [gek@kaos venv]$ python
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ftd2xx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gek/Projects/python/venv/ftdi/lib/python3.10/site-packages/ftd2xx/__init__.py", line 13, in <module>
    from . import aio
  File "/home/gek/Projects/python/venv/ftdi/lib/python3.10/site-packages/ftd2xx/aio/__init__.py", line 5, in <module>
    from ..ftd2xx import *
  File "/home/gek/Projects/python/venv/ftdi/lib/python3.10/site-packages/ftd2xx/ftd2xx.py", line 19, in <module>
    from . import _ftd2xx_linux as _ft
  File "/home/gek/Projects/python/venv/ftdi/lib/python3.10/site-packages/ftd2xx/_ftd2xx_linux.py", line 86, in <module>
    class pthread_cond_t(Structure):
  File "/home/gek/Projects/python/venv/ftdi/lib/python3.10/site-packages/ftd2xx/_ftd2xx_linux.py", line 92, in pthread_cond_t
    ("__align", __pthread_cond_align_t),
NameError: name '_pthread_cond_t__pthread_cond_align_t' is not defined
>>> 
`
Not sure what logs you would like.

g

**Comment by krister-ts** [comment]
@snmishra I ran into this as well but fixed in PR #46. PID/VID functions were also not imported

**Comment by snmishra** [comment]
Ah @krister-ts I thought I had merged #46, but looks like there are few failing checks.

**Comment by snmishra** [comment]
Sorry @gek47 for the wild-goose chase. I just merged #46. Could you check again?

**Comment by gek47** [comment]
created a new virtual environment, install and imported ok, no errors.  I'll do more testing over the next couple of days.

Thanks for your work on this project.  I prefer it over other FTDI python libs.

You can close this issue

g

**Comment by snmishra** [comment]
Thanks for reporting this @gek47 and working with us. I've released 1.3.0b2 to PyPI. If all looks good we can release 1.3.0 (it's been a while since the last release). Please add to the 1.3.0b2 discussion in #49
