### ISSUE TITLE
getModemStatus() returns None value

### ISSUE THREAD

**Issue by abuzarra** [snmishra/ftd2xx#5]
in file /ftd2xx/ftd2xx.py the function getModemStatus() returns a None value instead of the modem status.

**Comment by abuzarra** [comment]
This is the patch:
diff --git a/ftd2xx/ftd2xx.py b/ftd2xx/ftd2xx.py
index 97929df..604fc7f 100644
--- a/ftd2xx/ftd2xx.py
+++ b/ftd2xx/ftd2xx.py
@@ -208,7 +208,7 @@ class FTD2XX(object):
     def getModemStatus(self):
         m = _ft.DWORD()
         call_ft(_ft.FT_GetModemStatus, self.handle, c.byref(m))
-        return None
+        return m.value
 
     def setChars(self, evch, evch_en, erch, erch_en):
         call_ft(_ft.FT_SetChars, self.handle, _ft.UCHAR(evch),

**Comment by catskull** [comment]
PR #6 fixes this

**Comment by snmishra** [comment]
Thanks @abuzarra and @catskull . PR #6 is now merged.
