### ISSUE TITLE
TypedDicts only exist in Python 3.7

### ISSUE THREAD

**Issue by hmaarrfk** [snmishra/ftd2xx#51]
https://github.com/snmishra/ftd2xx/blob/2026a00f15db907ad4180ef176e9173313fe7204/ftd2xx/ftd2xx.py#L12

You probably want to require python 3.8 in your pypi release so that those with python 3.7 don't accidently get broken system

**Comment by snmishra** [comment]
@hmaarrfk Thanks for finding this. Fixed in #52

**Comment by hmaarrfk** [comment]
Thanks for getting on this so quickly.

**Comment by snmishra** [comment]
@hmaarrfk Released 1.3.1 with fix. And thanks for packaging for conda-forge.
