### ISSUE TITLE
getComPortNumber is broken in version 1.3.0

### ISSUE THREAD

**Issue by AurelianTimu** [snmishra/ftd2xx#53]
**Describe the bug**
`getComPortNumber` is using a data type of `_ft.LONG()` which does not exist anymore for win32.

**To Reproduce**
Call `getComPortNumber` on an instance of `FTD2XX` after the FTDI device is opened via `open`.

**Expected behavior**
To return the actual COM port number

**Logs**
`AttributeError: module 'ftd2xx._ftd2xx' has no attribute 'LONG'`

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - Python Version: 3.10
 - FTDI driver version: 1.3.0

**Additional context**
It looks like the `LONG` data type is not imported from `ctypes` in the 1.3.0 win32 version of the driver (`_ftd2xx.py`).
On version 1.1.2 it works without problems.

**Comment by snmishra** [comment]
Should be fixed in 1.3.1. Please reopen if issues persists.

**Comment by nimblewi** [comment]
We are still facing issue i am using version 2.1. _PY_GetComPortNumber

**Comment by snmishra** [comment]
@nimblewi Please open a new issue and give more details. We don't have a version 2.1.
