### ISSUE TITLE
Wrong type hint in FTD2XX.setBitMode?

### ISSUE THREAD

**Issue by atnon** [snmishra/ftd2xx#61]
Hi!

I've been going over the documentation for D2XX and MPSSE during the day and it looks like the type hint for FTD2XX.setBitMode is incorrect compared to docs.

https://github.com/snmishra/ftd2xx/blob/b86dac42b9d00ee58556301a10becdf19b3ecf67/ftd2xx/ftd2xx.py#L455

Looking at the generated code, we have 
https://github.com/snmishra/ftd2xx/blob/b86dac42b9d00ee58556301a10becdf19b3ecf67/ftd2xx/_ftd2xx.py#L470-L475

whereas documentation [D2XX programmers guide](https://www.ftdichip.com/Support/Documents/ProgramGuides/D2XX_Programmer's_Guide(FT_000071).pdf) page 55/56 shows a slightly different interface which is used:
![image](https://user-images.githubusercontent.com/3219788/206417765-7f682d3d-1b0c-4c3d-99c3-7562578eb92e.png)

This is interestingly enough not consistent with the header file supplied from FTDI on their homepage with the d2xx driver:
```
FTD2XX_API
	FT_STATUS WINAPI FT_SetBitMode(
	FT_HANDLE ftHandle,
	UCHAR ucMask,
	UCHAR ucEnable
);
```

Either way, the ucMode needs to be settable depending on the mode used, which is outside the value range of the bool type hint, so I suggest changing the type hint to int. Please tell me if I've misinterpreted something here.

I'll follow up with a pull request if I have time.

**Comment by snmishra** [comment]
@atnon Thanks for finding the bug. May be the API has changed since I wrote that bit, or may be I made a mistake. I'm swamped with other stuff, so it will take me a while to get to it. Do you want to make a PR?

**Comment by atnon** [comment]
@snmishra I've created a pull request (#62 ) with this minor change and verified it the best I can. Please have a look when you are able to. 😊

**Comment by snmishra** [comment]
Thanks for the PR. Merged.
