### ISSUE TITLE
Supporting EEPROM features for later device revisions

### ISSUE THREAD

**Issue by tschlagi** [snmishra/ftd2xx#70]
**Is your feature request related to a problem? Please describe.**
Using the FT4232H one can not set its specific flags in eeprom. Eg. there is no `IfBIsFifo8` to be set.
According to FTDIs Programmers Guide [https://ftdichip.com/wp-content/uploads/2020/08/D2XX_Programmers_GuideFT_000071.pdf](url) page 43-49 there are up to nine device revisions that are enabled by setting the matching `Version` . The implemented list only contains entries up to version two. (The ninth revision needs version five)

**Describe the solution you'd like**
Adding the missing entries to support version four (FT4232H) at least. Changes have to be made in the following lists: `ftd2xx.py` `ProgramData` and  `_ftd2xx.py` `ft_program_data`. Those entries have to be in the right order and have to include every preceding version's entry. The complete list can be found in the Programmers Guide. Suggested terms for those entries are given in the FTDI EEPROM Examples [https://ftdichip.com/wp-content/uploads/2020/08/AN_428-D2XX-EEPROM-Programming-Examples.pdf](url). E.g. page 13+14 for version three (FT2232H).
Finally to enable the added version, `ftd2xx.py` `Version=2` has to be changed to `Version=4`
This fix should be downward compatible with devices using a lower version. I tested this for FT2232H (version three) and everything worked fine.

I already implemented this solution and will create a PR.

**Comment by snmishra** [comment]
Thanks for the contribution @tschlagi! Released in 1.3.3
