### ISSUE TITLE
Add __del__ method

### ISSUE THREAD

**Issue by heke-pp** [snmishra/ftd2xx#72]
**Is your feature request related to a problem? Please describe.**
If the execution is terminated (e.g. by unhandled exception), the connection is not closed.

**Describe the solution you'd like**
Adding __del__ magic method to the FTD2XX class.
It is automatically called if the instance is destroyed.

`    def __del__(self):
        self.close()`

**Describe alternatives you've considered**
Considered having a beer.

**Comment by snmishra** [comment]
Beer is always a better alternative :)

Using `FTD2XX` as a context manager is a better bet. This project needs some docs desperately!

```
with ftd2xx.open(...):
   ...
```
