### ISSUE TITLE
Python 3.7 + "pip install ftd2xx" --> error in "import ftd2xx"

### ISSUE THREAD

**Issue by bavcol** [snmishra/ftd2xx#81]
**Describe the bug**

For legacy reasons I am using python 3.7 with ftd2xx (installed via pip).
_import ftd2xx_ fails with the following error:

> Traceback (most recent call last):
>   File "foobar.py", line 1, in <module>
>     import ftd2xx
>   File "C:\Python\WPy64-3760\python-3.7.6.amd64\lib\site-packages\ftd2xx\__init__.py", line 13, in <module>
>     from .ftd2xx import (
>   File "C:\Python\WPy64-3760\python-3.7.6.amd64\lib\site-packages\ftd2xx\ftd2xx.py", line 343, in <module>
>     class FTD2XX(AbstractContextManager["FTD2XX"]):
> TypeError: 'ABCMeta' object is not subscriptable

**To Reproduce**
1. Install python 3.7.
2. In cmd: _pip install ftd2xx_
3. In python: _import ftd2xx_

**Expected behavior**
_import ftd2xx_ does not raise error.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - Python Version: 3.7.6
 - FTDI driver version: 2.12.36.4

**Additional context**
Downgrading ftd2xx from v1.3.5 (installed by pip) to v1.3.3 resolved the issue for me.

**Comment by snmishra** [comment]
Sorry 3.7 is no longer supported
